name: Update all GitHub Pages sites

on:
  schedule:
    - cron: "* * * * *"

jobs:
  github-pages:
    runs-on: ubuntu-latest
    name: Update GitHub Pages initiatives
    steps:
      - name: Jekyll update github pages without new commit
        uses: DP6/jekyll-update-pages-action@v1.0.1
        with:
          DEPLOY_TOKEN: ${{ secrets.DeployTest }}
          USER: ${{ secrets.Hendryvwendel }}
          FILTER: "is%3Apublic%20org%3Adp6"
